blank_issues_enabled: true
contact_links:
  - name: Allgemeine Anfrage
    url: https://annaweber.art/contact
    about: FÃ¼r allgemeine Anfragen nutzen Sie bitte das Kontaktformular auf der Website.
